// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Sanaruca/condominio/internal/administracion/models/cuota/estadoproyecto"
	"github.com/Sanaruca/condominio/internal/administracion/models/deuda/estadodeuda"
	"github.com/Sanaruca/condominio/internal/administracion/types/tipodecuota"
	"github.com/Sanaruca/condominio/internal/core/common/mes"
	"github.com/Sanaruca/condominio/internal/core/common/moneda"
	"github.com/Sanaruca/condominio/internal/finanzas/types/metodoperacion"
	"github.com/Sanaruca/condominio/internal/finanzas/types/roldestinoperacion"
	"github.com/Sanaruca/condominio/internal/finanzas/types/tipoperacion"
	"github.com/Sanaruca/condominio/internal/unidades/models/sujeto"
	"github.com/Sanaruca/condominio/internal/unidades/models/unidad/estadounidad"
)

type Cuota interface {
	IsCuota()
	GetID() string
	GetMonto() float64
	GetMes() mes.Mes
	GetAnio() int32
	GetRegistro() time.Time
	GetActualizacion() time.Time
	GetRecaudacion() *Recaudacion
	GetGastos() []GastoType
}

type CuotaType interface {
	IsCuotaType()
}

type DeudaCuota interface {
	IsDeudaCuota()
	GetID() string
	GetNombre() string
	GetMonto() float64
	GetMes() mes.Mes
	GetAnio() int32
	GetRegistro() time.Time
	GetActualizacion() time.Time
}

type DeudaCuotaType interface {
	IsDeudaCuotaType()
}

type Gasto interface {
	IsIOperacion()
	IsGasto()
	GetOperacion() string
	GetTransaccion() *string
	GetCuota() *string
	GetFecha() time.Time
	GetConcepto() string
	GetMonto() float64
	GetMoneda() moneda.Moneda
	GetTotal() float64
	GetMetodo() metodoperacion.MetodoDeOperacion
	GetTasa() float64
	GetRegistradoPor() string
	GetRegistro() time.Time
}

type GastoType interface {
	IsGastoType()
}

type IOperacion interface {
	IsIOperacion()
	GetOperacion() string
	GetConcepto() string
	GetMonto() float64
	GetFecha() time.Time
	GetMoneda() moneda.Moneda
	GetMetodo() metodoperacion.MetodoDeOperacion
	GetTasa() float64
	GetTotal() float64
	GetRegistradoPor() string
	GetRegistro() time.Time
}

type OperacionType interface {
	IsOperacionType()
}

type Sujeto interface {
	IsSujeto()
	GetID() string
	GetEmail() string
	GetTelefono() string
	GetCedula() string
	GetRegistro() time.Time
	GetDisplayName() string
}

type Abono struct {
	Pago  string    `json:"pago"`
	Monto float64   `json:"monto"`
	Fecha time.Time `json:"fecha"`
}

type BooleanCondition struct {
	Eq  graphql.Omittable[*bool] `json:"eq,omitempty"`
	Neq graphql.Omittable[*bool] `json:"neq,omitempty"`
}

type CuotaEspecial struct {
	ID            string       `json:"id"`
	Monto         float64      `json:"monto"`
	Mes           mes.Mes      `json:"mes"`
	Anio          int32        `json:"anio"`
	Registro      time.Time    `json:"registro"`
	Actualizacion time.Time    `json:"actualizacion"`
	Detalles      *Proyecto    `json:"detalles"`
	Recaudacion   *Recaudacion `json:"recaudacion"`
	Gastos        []GastoType  `json:"gastos"`
}

func (CuotaEspecial) IsCuota()                          {}
func (this CuotaEspecial) GetID() string                { return this.ID }
func (this CuotaEspecial) GetMonto() float64            { return this.Monto }
func (this CuotaEspecial) GetMes() mes.Mes              { return this.Mes }
func (this CuotaEspecial) GetAnio() int32               { return this.Anio }
func (this CuotaEspecial) GetRegistro() time.Time       { return this.Registro }
func (this CuotaEspecial) GetActualizacion() time.Time  { return this.Actualizacion }
func (this CuotaEspecial) GetRecaudacion() *Recaudacion { return this.Recaudacion }
func (this CuotaEspecial) GetGastos() []GastoType {
	if this.Gastos == nil {
		return nil
	}
	interfaceSlice := make([]GastoType, 0, len(this.Gastos))
	for _, concrete := range this.Gastos {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

func (CuotaEspecial) IsCuotaType() {}

type CuotaFilter struct {
	ID    *StringCondition `json:"id,omitempty"`
	Monto *IntCondition    `json:"monto,omitempty"`
	And   []*CuotaFilter   `json:"and,omitempty"`
	Or    []*CuotaFilter   `json:"or,omitempty"`
	Not   *CuotaFilter     `json:"not,omitempty"`
}

type CuotaRegular struct {
	ID            string       `json:"id"`
	Monto         float64      `json:"monto"`
	Mes           mes.Mes      `json:"mes"`
	Anio          int32        `json:"anio"`
	Registro      time.Time    `json:"registro"`
	Actualizacion time.Time    `json:"actualizacion"`
	Recaudacion   *Recaudacion `json:"recaudacion"`
	Gastos        []GastoType  `json:"gastos"`
}

func (CuotaRegular) IsCuota()                          {}
func (this CuotaRegular) GetID() string                { return this.ID }
func (this CuotaRegular) GetMonto() float64            { return this.Monto }
func (this CuotaRegular) GetMes() mes.Mes              { return this.Mes }
func (this CuotaRegular) GetAnio() int32               { return this.Anio }
func (this CuotaRegular) GetRegistro() time.Time       { return this.Registro }
func (this CuotaRegular) GetActualizacion() time.Time  { return this.Actualizacion }
func (this CuotaRegular) GetRecaudacion() *Recaudacion { return this.Recaudacion }
func (this CuotaRegular) GetGastos() []GastoType {
	if this.Gastos == nil {
		return nil
	}
	interfaceSlice := make([]GastoType, 0, len(this.Gastos))
	for _, concrete := range this.Gastos {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

func (CuotaRegular) IsCuotaType() {}

type CuotaSemilla struct {
	ID            string       `json:"id"`
	Monto         float64      `json:"monto"`
	Mes           mes.Mes      `json:"mes"`
	Anio          int32        `json:"anio"`
	Registro      time.Time    `json:"registro"`
	Actualizacion time.Time    `json:"actualizacion"`
	Recaudacion   *Recaudacion `json:"recaudacion"`
	Gastos        []GastoType  `json:"gastos"`
}

func (CuotaSemilla) IsCuota()                          {}
func (this CuotaSemilla) GetID() string                { return this.ID }
func (this CuotaSemilla) GetMonto() float64            { return this.Monto }
func (this CuotaSemilla) GetMes() mes.Mes              { return this.Mes }
func (this CuotaSemilla) GetAnio() int32               { return this.Anio }
func (this CuotaSemilla) GetRegistro() time.Time       { return this.Registro }
func (this CuotaSemilla) GetActualizacion() time.Time  { return this.Actualizacion }
func (this CuotaSemilla) GetRecaudacion() *Recaudacion { return this.Recaudacion }
func (this CuotaSemilla) GetGastos() []GastoType {
	if this.Gastos == nil {
		return nil
	}
	interfaceSlice := make([]GastoType, 0, len(this.Gastos))
	for _, concrete := range this.Gastos {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

func (CuotaSemilla) IsCuotaType() {}

type Deuda struct {
	ID       string                    `json:"id"`
	Estado   estadodeuda.EstadoDeDeuda `json:"estado"`
	Cuota    DeudaCuotaType            `json:"cuota"`
	Unidad   *UnidadIdentifiers        `json:"unidad"`
	Titular  *DeudaTitular             `json:"titular,omitempty"`
	Monto    float64                   `json:"monto"`
	Deuda    float64                   `json:"deuda"`
	Abonos   []*Abono                  `json:"abonos,omitempty"`
	Registro time.Time                 `json:"registro"`
}

type DeudaFilter struct {
	Cuota  *StringCondition `json:"cuota,omitempty"`
	Unidad *StringCondition `json:"unidad,omitempty"`
	Estado *StringCondition `json:"estado,omitempty"`
	And    []*DeudaFilter   `json:"and,omitempty"`
	Or     []*DeudaFilter   `json:"or,omitempty"`
	Not    *DeudaFilter     `json:"not,omitempty"`
}

type DeudaCuotaEspecial struct {
	ID            string    `json:"id"`
	Nombre        string    `json:"nombre"`
	Monto         float64   `json:"monto"`
	Mes           mes.Mes   `json:"mes"`
	Anio          int32     `json:"anio"`
	Registro      time.Time `json:"registro"`
	Actualizacion time.Time `json:"actualizacion"`
}

func (DeudaCuotaEspecial) IsDeudaCuota()                    {}
func (this DeudaCuotaEspecial) GetID() string               { return this.ID }
func (this DeudaCuotaEspecial) GetNombre() string           { return this.Nombre }
func (this DeudaCuotaEspecial) GetMonto() float64           { return this.Monto }
func (this DeudaCuotaEspecial) GetMes() mes.Mes             { return this.Mes }
func (this DeudaCuotaEspecial) GetAnio() int32              { return this.Anio }
func (this DeudaCuotaEspecial) GetRegistro() time.Time      { return this.Registro }
func (this DeudaCuotaEspecial) GetActualizacion() time.Time { return this.Actualizacion }

func (DeudaCuotaEspecial) IsDeudaCuotaType() {}

type DeudaCuotaRegular struct {
	ID            string    `json:"id"`
	Nombre        string    `json:"nombre"`
	Monto         float64   `json:"monto"`
	Mes           mes.Mes   `json:"mes"`
	Anio          int32     `json:"anio"`
	Registro      time.Time `json:"registro"`
	Actualizacion time.Time `json:"actualizacion"`
}

func (DeudaCuotaRegular) IsDeudaCuota()                    {}
func (this DeudaCuotaRegular) GetID() string               { return this.ID }
func (this DeudaCuotaRegular) GetNombre() string           { return this.Nombre }
func (this DeudaCuotaRegular) GetMonto() float64           { return this.Monto }
func (this DeudaCuotaRegular) GetMes() mes.Mes             { return this.Mes }
func (this DeudaCuotaRegular) GetAnio() int32              { return this.Anio }
func (this DeudaCuotaRegular) GetRegistro() time.Time      { return this.Registro }
func (this DeudaCuotaRegular) GetActualizacion() time.Time { return this.Actualizacion }

func (DeudaCuotaRegular) IsDeudaCuotaType() {}

type DeudaCuotaSemilla struct {
	ID            string    `json:"id"`
	Nombre        string    `json:"nombre"`
	Monto         float64   `json:"monto"`
	Mes           mes.Mes   `json:"mes"`
	Anio          int32     `json:"anio"`
	Registro      time.Time `json:"registro"`
	Actualizacion time.Time `json:"actualizacion"`
}

func (DeudaCuotaSemilla) IsDeudaCuota()                    {}
func (this DeudaCuotaSemilla) GetID() string               { return this.ID }
func (this DeudaCuotaSemilla) GetNombre() string           { return this.Nombre }
func (this DeudaCuotaSemilla) GetMonto() float64           { return this.Monto }
func (this DeudaCuotaSemilla) GetMes() mes.Mes             { return this.Mes }
func (this DeudaCuotaSemilla) GetAnio() int32              { return this.Anio }
func (this DeudaCuotaSemilla) GetRegistro() time.Time      { return this.Registro }
func (this DeudaCuotaSemilla) GetActualizacion() time.Time { return this.Actualizacion }

func (DeudaCuotaSemilla) IsDeudaCuotaType() {}

type DeudaTitular struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	Telefono    string `json:"telefono"`
	Cedula      string `json:"cedula"`
	DisplayName string `json:"display_name"`
}

type Ente struct {
	ID            string    `json:"id"`
	RazonSocial   string    `json:"razon_social"`
	Email         string    `json:"email"`
	Telefono      string    `json:"telefono"`
	Cedula        string    `json:"cedula"`
	Representante *Persona  `json:"representante"`
	Registro      time.Time `json:"registro"`
	DisplayName   string    `json:"display_name"`
}

func (Ente) IsSujeto()                   {}
func (this Ente) GetID() string          { return this.ID }
func (this Ente) GetEmail() string       { return this.Email }
func (this Ente) GetTelefono() string    { return this.Telefono }
func (this Ente) GetCedula() string      { return this.Cedula }
func (this Ente) GetRegistro() time.Time { return this.Registro }
func (this Ente) GetDisplayName() string { return this.DisplayName }

func (Ente) IsTitular() {}

type GastoACondominio struct {
	Operacion     string                           `json:"operacion"`
	Transaccion   *string                          `json:"transaccion,omitempty"`
	Cuota         *string                          `json:"cuota,omitempty"`
	Fecha         time.Time                        `json:"fecha"`
	Concepto      string                           `json:"concepto"`
	Monto         float64                          `json:"monto"`
	Moneda        moneda.Moneda                    `json:"moneda"`
	Total         float64                          `json:"total"`
	Metodo        metodoperacion.MetodoDeOperacion `json:"metodo"`
	Tasa          float64                          `json:"tasa"`
	RegistradoPor string                           `json:"registrado_por"`
	Registro      time.Time                        `json:"registro"`
}

func (GastoACondominio) IsGasto()                                         {}
func (this GastoACondominio) GetOperacion() string                        { return this.Operacion }
func (this GastoACondominio) GetTransaccion() *string                     { return this.Transaccion }
func (this GastoACondominio) GetCuota() *string                           { return this.Cuota }
func (this GastoACondominio) GetFecha() time.Time                         { return this.Fecha }
func (this GastoACondominio) GetConcepto() string                         { return this.Concepto }
func (this GastoACondominio) GetMonto() float64                           { return this.Monto }
func (this GastoACondominio) GetMoneda() moneda.Moneda                    { return this.Moneda }
func (this GastoACondominio) GetTotal() float64                           { return this.Total }
func (this GastoACondominio) GetMetodo() metodoperacion.MetodoDeOperacion { return this.Metodo }
func (this GastoACondominio) GetTasa() float64                            { return this.Tasa }
func (this GastoACondominio) GetRegistradoPor() string                    { return this.RegistradoPor }
func (this GastoACondominio) GetRegistro() time.Time                      { return this.Registro }

func (GastoACondominio) IsIOperacion() {}

func (GastoACondominio) IsGastoType() {}

func (GastoACondominio) IsOperacionType() {}

type GastoAProveedor struct {
	Operacion     string                           `json:"operacion"`
	Transaccion   *string                          `json:"transaccion,omitempty"`
	Cuota         *string                          `json:"cuota,omitempty"`
	Fecha         time.Time                        `json:"fecha"`
	Concepto      string                           `json:"concepto"`
	Monto         float64                          `json:"monto"`
	Moneda        moneda.Moneda                    `json:"moneda"`
	Total         float64                          `json:"total"`
	Metodo        metodoperacion.MetodoDeOperacion `json:"metodo"`
	Tasa          float64                          `json:"tasa"`
	RegistradoPor string                           `json:"registrado_por"`
	Registro      time.Time                        `json:"registro"`
	Proveedor     *Proveedor                       `json:"proveedor"`
}

func (GastoAProveedor) IsGasto()                                         {}
func (this GastoAProveedor) GetOperacion() string                        { return this.Operacion }
func (this GastoAProveedor) GetTransaccion() *string                     { return this.Transaccion }
func (this GastoAProveedor) GetCuota() *string                           { return this.Cuota }
func (this GastoAProveedor) GetFecha() time.Time                         { return this.Fecha }
func (this GastoAProveedor) GetConcepto() string                         { return this.Concepto }
func (this GastoAProveedor) GetMonto() float64                           { return this.Monto }
func (this GastoAProveedor) GetMoneda() moneda.Moneda                    { return this.Moneda }
func (this GastoAProveedor) GetTotal() float64                           { return this.Total }
func (this GastoAProveedor) GetMetodo() metodoperacion.MetodoDeOperacion { return this.Metodo }
func (this GastoAProveedor) GetTasa() float64                            { return this.Tasa }
func (this GastoAProveedor) GetRegistradoPor() string                    { return this.RegistradoPor }
func (this GastoAProveedor) GetRegistro() time.Time                      { return this.Registro }

func (GastoAProveedor) IsIOperacion() {}

func (GastoAProveedor) IsGastoType() {}

func (GastoAProveedor) IsOperacionType() {}

type GastoFilter struct {
	Concepto *StringCondition `json:"concepto,omitempty"`
	Cuota    *StringCondition `json:"cuota,omitempty"`
	And      []*GastoFilter   `json:"and,omitempty"`
	Or       []*GastoFilter   `json:"or,omitempty"`
	Not      *GastoFilter     `json:"not,omitempty"`
}

type IntCondition struct {
	Eq  graphql.Omittable[*int32] `json:"eq,omitempty"`
	Neq graphql.Omittable[*int32] `json:"neq,omitempty"`
	Gt  *int32                    `json:"gt,omitempty"`
	Gte *int32                    `json:"gte,omitempty"`
	Lt  *int32                    `json:"lt,omitempty"`
	Lte *int32                    `json:"lte,omitempty"`
}

type LoginCredentialsDto struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type ObtenerProveedoresDto struct {
	ID  *StringCondition         `json:"id,omitempty"`
	And []*ObtenerProveedoresDto `json:"and,omitempty"`
	Or  []*ObtenerProveedoresDto `json:"or,omitempty"`
	Not *ObtenerProveedoresDto   `json:"not,omitempty"`
}

type Operacion struct {
	ID            string                                   `json:"id"`
	Fecha         time.Time                                `json:"fecha"`
	Concepto      string                                   `json:"concepto"`
	Monto         float64                                  `json:"monto"`
	Moneda        moneda.Moneda                            `json:"moneda"`
	Metodo        metodoperacion.MetodoDeOperacion         `json:"metodo"`
	Total         float64                                  `json:"total"`
	Tasa          float64                                  `json:"tasa"`
	Tipo          tipoperacion.TipoDeOperacion             `json:"tipo"`
	Rol           roldestinoperacion.RolDestinoDeOperacion `json:"rol"`
	Cuota         *string                                  `json:"cuota,omitempty"`
	RegistradoPor string                                   `json:"registrado_por"`
	Registro      time.Time                                `json:"registro"`
	UnidadCodigo  *string                                  `json:"unidad_codigo,omitempty"`
	Proveedor     *string                                  `json:"proveedor,omitempty"`
	Unidad        *Unidad                                  `json:"unidad,omitempty"`
}

type OperacionFilter struct {
	Concepto        *StringCondition   `json:"concepto,omitempty"`
	Unidad          *StringCondition   `json:"unidad,omitempty"`
	Tipo            *StringCondition   `json:"tipo,omitempty"`
	ProveedorNombre *StringCondition   `json:"proveedor_nombre,omitempty"`
	And             []*OperacionFilter `json:"and,omitempty"`
	Or              []*OperacionFilter `json:"or,omitempty"`
	Not             *OperacionFilter   `json:"not,omitempty"`
}

type PaginatedCuota struct {
	Data  []CuotaType `json:"data"`
	Total int32       `json:"total"`
	Page  int32       `json:"page"`
	Pages int32       `json:"pages"`
	Limit int32       `json:"limit"`
}

type PaginatedDeuda struct {
	Data  []*Deuda `json:"data"`
	Total int32    `json:"total"`
	Page  int32    `json:"page"`
	Pages int32    `json:"pages"`
	Limit int32    `json:"limit"`
}

type PaginatedGasto struct {
	Data  []GastoType `json:"data"`
	Total int32       `json:"total"`
	Page  int32       `json:"page"`
	Pages int32       `json:"pages"`
	Limit int32       `json:"limit"`
}

type PaginatedOperacion struct {
	Data  []OperacionType `json:"data"`
	Total int32           `json:"total"`
	Page  int32           `json:"page"`
	Pages int32           `json:"pages"`
	Limit int32           `json:"limit"`
}

type PaginatedPago struct {
	Data  []*Pago `json:"data"`
	Total int32   `json:"total"`
	Page  int32   `json:"page"`
	Pages int32   `json:"pages"`
	Limit int32   `json:"limit"`
}

type PaginatedUnidad struct {
	Data  []*Unidad `json:"data"`
	Total int32     `json:"total"`
	Page  int32     `json:"page"`
	Pages int32     `json:"pages"`
	Limit int32     `json:"limit"`
}

type Paginator struct {
	Page  int32 `json:"page"`
	Limit int32 `json:"limit"`
}

type Pago struct {
	Operacion     string                           `json:"operacion"`
	Unidad        *UnidadIdentifiers               `json:"unidad"`
	Fecha         time.Time                        `json:"fecha"`
	Concepto      string                           `json:"concepto"`
	Monto         float64                          `json:"monto"`
	Total         float64                          `json:"total"`
	Moneda        moneda.Moneda                    `json:"moneda"`
	Metodo        metodoperacion.MetodoDeOperacion `json:"metodo"`
	Tasa          float64                          `json:"tasa"`
	RegistradoPor string                           `json:"registrado_por"`
	Registro      time.Time                        `json:"registro"`
}

func (Pago) IsIOperacion()                                    {}
func (this Pago) GetOperacion() string                        { return this.Operacion }
func (this Pago) GetConcepto() string                         { return this.Concepto }
func (this Pago) GetMonto() float64                           { return this.Monto }
func (this Pago) GetFecha() time.Time                         { return this.Fecha }
func (this Pago) GetMoneda() moneda.Moneda                    { return this.Moneda }
func (this Pago) GetMetodo() metodoperacion.MetodoDeOperacion { return this.Metodo }
func (this Pago) GetTasa() float64                            { return this.Tasa }
func (this Pago) GetTotal() float64                           { return this.Total }
func (this Pago) GetRegistradoPor() string                    { return this.RegistradoPor }
func (this Pago) GetRegistro() time.Time                      { return this.Registro }

func (Pago) IsOperacionType() {}

type PagoFilter struct {
	Unidad *StringCondition `json:"unidad,omitempty"`
	And    []*PagoFilter    `json:"and,omitempty"`
	Or     []*PagoFilter    `json:"or,omitempty"`
	Not    *PagoFilter      `json:"not,omitempty"`
}

type PeriodoDisponible struct {
	Anio int32   `json:"anio"`
	Mes  mes.Mes `json:"mes"`
}

type Persona struct {
	ID          string    `json:"id"`
	Nombres     string    `json:"nombres"`
	Apellidos   string    `json:"apellidos"`
	Email       string    `json:"email"`
	Telefono    string    `json:"telefono"`
	Cedula      string    `json:"cedula"`
	Registro    time.Time `json:"registro"`
	DisplayName string    `json:"display_name"`
}

func (Persona) IsSujeto()                   {}
func (this Persona) GetID() string          { return this.ID }
func (this Persona) GetEmail() string       { return this.Email }
func (this Persona) GetTelefono() string    { return this.Telefono }
func (this Persona) GetCedula() string      { return this.Cedula }
func (this Persona) GetRegistro() time.Time { return this.Registro }
func (this Persona) GetDisplayName() string { return this.DisplayName }

func (Persona) IsTitular() {}

type Proveedor struct {
	ID            string    `json:"id"`
	Rif           string    `json:"rif"`
	Nombre        string    `json:"nombre"`
	Email         *string   `json:"email,omitempty"`
	Telefono      *string   `json:"telefono,omitempty"`
	Direccion     *string   `json:"direccion,omitempty"`
	CreadoEn      time.Time `json:"creado_en"`
	ActualizadoEn time.Time `json:"actualizado_en"`
}

type Proyecto struct {
	Titulo         string                          `json:"titulo"`
	Estado         estadoproyecto.EstadoDeProyecto `json:"estado"`
	Descripcion    string                          `json:"descripcion"`
	Justificacion  string                          `json:"justificacion"`
	FechaLimite    time.Time                       `json:"fecha_limite"`
	InteresPorMora float64                         `json:"interes_por_mora"`
	Registro       time.Time                       `json:"registro"`
	Actualizacion  time.Time                       `json:"actualizacion"`
}

type Query struct {
}

type Recaudacion struct {
	Moneda             moneda.Moneda `json:"moneda"`
	MontoEstimado      float64       `json:"monto_estimado"`
	MontoRecaudado     float64       `json:"monto_recaudado"`
	MontoPendiente     float64       `json:"monto_pendiente"`
	PagosAsociados     int32         `json:"pagos_asociados"`
	Unidades           int32         `json:"unidades"`
	UnidadesAplicadas  int32         `json:"unidades_aplicadas"`
	UnidadesSolventes  int32         `json:"unidades_solventes"`
	UnidadesPendientes int32         `json:"unidades_pendientes"`
}

type RegistrarCuotaDto struct {
	Gastos        []string                `json:"gastos"`
	Tipo          tipodecuota.TipoDeCuota `json:"tipo"`
	Mes           *mes.Mes                `json:"mes,omitempty"`
	Anio          *int32                  `json:"anio,omitempty"`
	FechaLimite   *time.Time              `json:"fecha_limite,omitempty"`
	Titulo        *string                 `json:"titulo,omitempty"`
	Descripcion   *string                 `json:"descripcion,omitempty"`
	Justificacion *string                 `json:"justificacion,omitempty"`
}

type RegistrarGastoDto struct {
	Concepto   string                           `json:"concepto"`
	Referencia *string                          `json:"referencia,omitempty"`
	Metodo     metodoperacion.MetodoDeOperacion `json:"metodo"`
	Proveedor  string                           `json:"proveedor"`
	Moneda     *moneda.Moneda                   `json:"moneda,omitempty"`
	Monto      int32                            `json:"monto"`
	Tasa       int32                            `json:"tasa"`
	Fecha      *time.Time                       `json:"fecha,omitempty"`
}

type RegistrarPagoDto struct {
	Concepto   *string                          `json:"concepto,omitempty"`
	Unidad     string                           `json:"unidad"`
	Moneda     moneda.Moneda                    `json:"moneda"`
	Metodo     metodoperacion.MetodoDeOperacion `json:"metodo"`
	Monto      int32                            `json:"monto"`
	Tasa       int32                            `json:"tasa"`
	Referencia *string                          `json:"referencia,omitempty"`
	Fecha      *time.Time                       `json:"fecha,omitempty"`
}

type RegistrarProveedorDto struct {
	Rif       string  `json:"rif"`
	Nombre    string  `json:"nombre"`
	Email     string  `json:"email"`
	Telefono  string  `json:"telefono"`
	Direccion *string `json:"direccion,omitempty"`
}

type RegistrarSujetoDto struct {
	Tipo               sujeto.TipoDeSujeto `json:"tipo"`
	DocumentoIdentidad string              `json:"documento_identidad"`
	Nombres            *string             `json:"nombres,omitempty"`
	Apellidos          *string             `json:"apellidos,omitempty"`
	RazonSocial        *string             `json:"razon_social,omitempty"`
	Representante      *string             `json:"representante,omitempty"`
	Email              string              `json:"email"`
	Telefono           string              `json:"telefono"`
}

type RegistrarUnidadDto struct {
	Codigo          string                      `json:"codigo"`
	Estado          estadounidad.EstadoDeUnidad `json:"estado"`
	TitularPrimario *string                     `json:"titular_primario,omitempty"`
	Contacto        *string                     `json:"contacto,omitempty"`
	Descripcion     *string                     `json:"descripcion,omitempty"`
}

type StringCondition struct {
	Eq    graphql.Omittable[*string] `json:"eq,omitempty"`
	Neq   graphql.Omittable[*string] `json:"neq,omitempty"`
	Like  *string                    `json:"like,omitempty"`
	Regex *string                    `json:"regex,omitempty"`
	In    []*string                  `json:"in,omitempty"`
}

type Tasa struct {
	Valor  float64 `json:"valor"`
	Fuente string  `json:"fuente"`
	Fecha  string  `json:"fecha"`
	Tipo   string  `json:"tipo"`
	Moneda string  `json:"moneda"`
}

type Unidad struct {
	ID              string                      `json:"id"`
	Codigo          string                      `json:"codigo"`
	Estado          estadounidad.EstadoDeUnidad `json:"estado"`
	TitularPrimario Titular                     `json:"titular_primario,omitempty"`
	Titulares       []Titular                   `json:"titulares,omitempty"`
	Contacto        *Persona                    `json:"contacto,omitempty"`
	Deuda           float64                     `json:"deuda"`
	Wallet          float64                     `json:"wallet"`
}

type UnidadFilter struct {
	ID     *StringCondition `json:"id,omitempty"`
	Codigo *StringCondition `json:"codigo,omitempty"`
	Estado *StringCondition `json:"estado,omitempty"`
	Deuda  *IntCondition    `json:"deuda,omitempty"`
	And    []*UnidadFilter  `json:"and,omitempty"`
	Or     []*UnidadFilter  `json:"or,omitempty"`
	Not    *UnidadFilter    `json:"not,omitempty"`
}

type UnidadIdentifiers struct {
	ID     string `json:"id"`
	Codigo string `json:"codigo"`
}

type UnidadesResumen struct {
	TotalUnidades         int32   `json:"total_unidades"`
	UnidadesActivas       int32   `json:"unidades_activas"`
	UnidadesInhabitadas   int32   `json:"unidades_inhabitadas"`
	UnidadesExentas       int32   `json:"unidades_exentas"`
	UnidadesEnLitigio     int32   `json:"unidades_en_litigio"`
	UnidadesSuspendidas   int32   `json:"unidades_suspendidas"`
	UnidadesPreventa      int32   `json:"unidades_preventa"`
	UnidadesConPendientes int32   `json:"unidades_con_pendientes"`
	UnidadesSolventes     int32   `json:"unidades_solventes"`
	TotalPendiente        float64 `json:"total_pendiente"`
	TotalAsignado         float64 `json:"total_asignado"`
}
