// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seeds/index.ts -s views mocks/mock_grande denormalizar_unidades",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
