package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/unidades/app/command"
	"github.com/Sanaruca/condominio/internal/unidades/models/sujeto"
)

// ActualizarSujeto is the resolver for the actualizarSujeto field.
func (r *mutationResolver) ActualizarSujeto(ctx context.Context, id string, data model.ActualizarSujetoDto) (bool, error) {
	admin, err := cc.Wrap(ctx).AsAdmin()

	if err != nil {
		return false, err
	}

	_, err = r.Unidades.Commands.ActualizarSujeto.Exec(admin, command.ActualizarSujetoDTO{
		SujetoID:    sujeto.SujetoID(id),
		Email:       data.Email,
		Telefono:    data.Telefono,
		Nombres:     new(string),
		Apellidos:   new(string),
		RazonSocial: new(string),
	})

	if err != nil {
		return false, err
	}

	return true, nil
}
