package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/loaders"
	"github.com/Sanaruca/condominio/graph/model"
)

// Recaudacion is the resolver for the recaudacion field.
func (r *cuotaEspecialResolver) Recaudacion(ctx context.Context, obj *model.CuotaEspecial) (*model.Recaudacion, error) {
	return loaders.GetRecaudacion(ctx, obj.ID)
}

// Gastos is the resolver for the gastos field.
func (r *cuotaEspecialResolver) Gastos(ctx context.Context, obj *model.CuotaEspecial) ([]model.GastoType, error) {
	return resolverObtenerGastos(ctx, r.Resolver, obj.GetID())
}

// Recaudacion is the resolver for the recaudacion field.
func (r *cuotaRegularResolver) Recaudacion(ctx context.Context, obj *model.CuotaRegular) (*model.Recaudacion, error) {
	return loaders.GetRecaudacion(ctx, obj.ID)
}

// Gastos is the resolver for the gastos field.
func (r *cuotaRegularResolver) Gastos(ctx context.Context, obj *model.CuotaRegular) ([]model.GastoType, error) {
	return resolverObtenerGastos(ctx, r.Resolver, obj.GetID())
}

// Recaudacion is the resolver for the recaudacion field.
func (r *cuotaSemillaResolver) Recaudacion(ctx context.Context, obj *model.CuotaSemilla) (*model.Recaudacion, error) {
	return loaders.GetRecaudacion(ctx, obj.ID)
}

// Gastos is the resolver for the gastos field.
func (r *cuotaSemillaResolver) Gastos(ctx context.Context, obj *model.CuotaSemilla) ([]model.GastoType, error) {
	return resolverObtenerGastos(ctx, r.Resolver, obj.GetID())
}

// CuotaEspecial returns CuotaEspecialResolver implementation.
func (r *Resolver) CuotaEspecial() CuotaEspecialResolver { return &cuotaEspecialResolver{r} }

// CuotaRegular returns CuotaRegularResolver implementation.
func (r *Resolver) CuotaRegular() CuotaRegularResolver { return &cuotaRegularResolver{r} }

// CuotaSemilla returns CuotaSemillaResolver implementation.
func (r *Resolver) CuotaSemilla() CuotaSemillaResolver { return &cuotaSemillaResolver{r} }

type cuotaEspecialResolver struct{ *Resolver }
type cuotaRegularResolver struct{ *Resolver }
type cuotaSemillaResolver struct{ *Resolver }
