package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/administracion/app/query"
	corecontext "github.com/Sanaruca/condominio/internal/core/context"
)

// ObtenerCuotas is the resolver for the obtenerCuotas field.
func (r *queryResolver) ObtenerCuotas(ctx context.Context, filter *model.CuotaFilter, paginator *model.Paginator) (*model.PaginatedCuota, error) {
	baseContext, err := corecontext.Wrap(ctx).AsBase()

	if err != nil {
		return nil, err
	}

	cuotas, err := r.Administracion.Queries.ObtenerCuotas.Exec(baseContext, query.ObtenerCuotasDTO{
		Paginator: paginator.ToDomainPaginator(),
		Filter:    filter.ToFilter(),
	})

	if err != nil {
		return nil, err
	}

	data := make([]model.CuotaType, len(cuotas.Data))

	for i, cuota := range cuotas.Data {
		data[i] = model.CuotaTypeFromDomain(cuota)
	}

	return &model.PaginatedCuota{
		Data:  data,
		Total: int32(cuotas.Total),
		Page:  int32(cuotas.Page),
		Pages: int32(cuotas.Pages),
		Limit: int32(cuotas.Limit),
	}, nil
}
