package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Sanaruca/condominio/graph/model"
	"github.com/Sanaruca/condominio/internal/core"
	gormAdapter "github.com/Sanaruca/condominio/internal/core/adapters/gorm"
	"github.com/Sanaruca/condominio/internal/core/common"
	"github.com/Sanaruca/condominio/internal/core/common/filter"
	cc "github.com/Sanaruca/condominio/internal/core/context"
	"github.com/Sanaruca/condominio/internal/core/lib/logger"
	"github.com/Sanaruca/condominio/internal/finanzas/types/roldestinoperacion"
	"github.com/Sanaruca/condominio/internal/finanzas/types/tipoperacion"
	database "github.com/Sanaruca/condominio/internal/shared/adapters/gorm"
	"gorm.io/gorm"
)

// ObtenerPagos is the resolver for the obtenerPagos field.
func (r *queryResolver) ObtenerPagos(ctx context.Context, filtro *model.PagoFilter, paginador *model.Paginator) (*model.PaginatedPago, error) {
	_, e := cc.Wrap(ctx).AsAdmin()

	if e != nil {
		return nil, e
	}

	paginator := paginador.ToDomainPaginator()

	inputMap, mapErr := model.StructToMap(filtro)

	if mapErr != nil {
		return nil, core.WrapError(mapErr)
	}

	ftr, err := filter.Parse(inputMap)

	if err != nil {
		return nil, core.WrapError(err)
	}

	if err := filter.
		NewValidator(model.GetFilterSpec(filtro)).
		Validate(ftr); err != nil {
		return nil, core.WrapError(err)
	}

	rows, err := gorm.G[database.Operacion](r.db).
		Where("tipo = ? AND rol = ?", tipoperacion.Credito, roldestinoperacion.Unidad).
		Scopes(
			gormAdapter.GFilter(ftr, map[string][]string{"unidad": {"unidad_id", "unidad_codigo"}}),
			gormAdapter.GPaginate(paginator),
		).
		Order("fecha DESC").
		Find(ctx)

	if err != nil {
		return nil, core.WrapError(err)
	}

	total, err := gorm.G[database.Operacion](r.db).
		Where("tipo = ? AND rol = ?", tipoperacion.Credito, roldestinoperacion.Unidad).
		Scopes(
			gormAdapter.GFilter(ftr, map[string][]string{"unidad": {"unidad_id", "unidad_codigo"}}),
		).
		Count(ctx, "id")

	if err != nil {
		return nil, core.WrapError(err)
	}

	data := make([]*model.Pago, len(rows))

	for i, op := range rows {
		if op.UnidadCodigo == nil || op.UnidadID == nil {
			logger.ErrorCtx(ctx, nil, "Pago sin unidad",
				"unidad.id", op.UnidadID,
				"unidad.codigo", op.UnidadCodigo,
			)
			return nil, core.ErrInternal
		}
		data[i] = &model.Pago{
			Operacion: op.ID,
			Unidad: &model.UnidadIdentifiers{
				ID:     *op.UnidadID,
				Codigo: *op.UnidadCodigo,
			},
			Fecha:         op.Fecha,
			Concepto:      op.Concepto,
			Monto:         r.qf.Assemble(int64(op.Monto)).Float(),
			Moneda:        op.Moneda,
			Metodo:        op.Metodo,
			Tasa:          r.qf.Assemble(int64(op.Tasa)).Float(),
			RegistradoPor: op.RegistradoPor,
			Registro:      op.Registro,
			Total:         op.Total(r.qf).Float(),
		}
	}

	pagos := common.NewPaginated(data, int(total), paginator)

	return &model.PaginatedPago{
		Data:  pagos.Data,
		Total: int32(pagos.Total),
		Page:  int32(pagos.Page),
		Pages: int32(pagos.Pages),
		Limit: int32(pagos.Limit),
	}, e
}
