interface Cuota {
  id: ID!
  monto: Float!
  mes: Mes!
  anio: Int!
  registro: DateTime!
  actualizacion: DateTime!
  recaudacion: Recaudacion!
  gastos: [GastoType!]!
}

type CuotaRegular implements Cuota {
  id: ID!
  monto: Float!
  mes: Mes!
  anio: Int!
  registro: DateTime!
  actualizacion: DateTime!
  recaudacion: Recaudacion!
  gastos: [GastoType!]!
}

type CuotaEspecial implements Cuota {
  id: ID!
  monto: Float!
  mes: Mes!
  anio: Int!
  registro: DateTime!
  actualizacion: DateTime!
  detalles: Proyecto!
  recaudacion: Recaudacion!
  gastos: [GastoType!]!
}

type CuotaSemilla implements Cuota {
  id: ID!
  monto: Float!
  mes: Mes!
  anio: Int!
  registro: DateTime!
  actualizacion: DateTime!
  recaudacion: Recaudacion!
  gastos: [GastoType!]!
}

union CuotaType = CuotaRegular | CuotaEspecial | CuotaSemilla

type PaginatedCuota {
  data: [CuotaType!]!
  total: Int!
  page: Int!
  pages: Int!
  limit: Int!
}
