/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query EstadoPagosVilla($filtro: DeudaFilter, $paginador: Paginator) {\n    deudas: obtenerDeudas(filtro: $filtro, paginador: $paginador) {\n      data {\n        id\n        unidad {\n          id\n          codigo\n        }\n        titular {\n          id\n          display_name\n        }\n        monto\n        deuda\n        estado\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": typeof types.EstadoPagosVillaDocument,
    "\n  query CuotaPage($cuota_id: String!) {\n    cuota: obtenerCuota(id: $cuota_id) {\n      __typename\n      ... on Cuota {\n        id\n        mes\n        anio\n        monto\n        registro\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n              rif\n              telefono\n              email\n            }\n          }\n        }\n      }\n      ... on CuotaEspecial {\n        detalles {\n          titulo\n          descripcion\n          justificacion\n          fecha_limite\n          estado\n        }\n      }\n    }\n  }\n": typeof types.CuotaPageDocument,
    "\n  query CuotasPage($page: Int!, $limit: Int!) {\n    cuotas: obtenerCuotas(paginator: { limit: $limit, page: $page }) {\n      data {\n        __typename\n        ... on Cuota {\n          id\n          monto\n          mes\n          anio\n          registro\n          recaudacion {\n            unidades_aplicadas\n            pagos_asociados\n            monto_estimado\n            monto_recaudado\n            moneda\n          }\n        }\n\n        ... on CuotaEspecial {\n          detalles {\n            titulo\n            descripcion\n          }\n          recaudacion {\n            unidades_aplicadas\n            pagos_asociados\n            monto_estimado\n            monto_recaudado\n            moneda\n          }\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": typeof types.CuotasPageDocument,
    "\n  query RegistrarCuotaPage {\n    obtenerProveedores {\n      id\n      nombre\n    }\n  }\n": typeof types.RegistrarCuotaPageDocument,
    "\n  query DashboardPage {\n    proveedores: obtenerProveedores {\n      id\n      nombre\n    }\n  }\n": typeof types.DashboardPageDocument,
    "\n  query OperacionesPage($page: Int!, $filtro: OperacionFilter, $limit: Int!) {\n    proveedores: obtenerProveedores {\n      id\n      nombre\n    }\n\n    operaciones: obtenerOperaciones(\n      paginador: { limit: $limit, page: $page }\n      filtro: $filtro\n    ) {\n      data {\n        __typename\n\n        ... on IOperacion {\n          fecha\n          operacion\n          concepto\n          metodo\n          monto\n          moneda\n          registro\n          tasa\n          total\n        }\n\n        ... on GastoAProveedor {\n          proveedor {\n            nombre\n            rif\n            telefono\n            email\n          }\n        }\n\n        ... on Pago {\n          unidad {\n            id\n            codigo\n          }\n        }\n      }\n\n      limit\n      page\n      pages\n      total\n    }\n  }\n": typeof types.OperacionesPageDocument,
    "\n  query UnidadTitular($codigo: String!) {\n    unidad: obtenerUnidadPorCodigo(codigo: $codigo) {\n      codigo\n      titular_primario {\n        __typename\n        ... on Sujeto {\n          id\n          display_name\n          cedula\n          email\n          telefono\n        }\n      }\n    }\n  }\n": typeof types.UnidadTitularDocument,
    "\n  mutation Login($email: String!, $pass: String!) {\n    login(email: $email, password: $pass) {\n      token\n    }\n  }\n": typeof types.LoginDocument,
    "\n  query RegistrarPagoPage($codigo_like: String!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $codigo_like } }\n      paginator: { limit: 5, page: 1 }\n    ) {\n      data {\n        id\n        codigo\n      }\n    }\n  }\n": typeof types.RegistrarPagoPageDocument,
    "\n  query VillaDeudas($codigo: String!, $page: Int!, $limit: Int!) {\n    deudas: obtenerDeudas(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: $limit, page: $page }\n    ) {\n      data {\n        id\n        cuota {\n          __typename\n          ... on Deuda__Cuota {\n            id\n            nombre\n          }\n        }\n        deuda\n        monto\n        estado\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": typeof types.VillaDeudasDocument,
    "\n  mutation EditarTitular($id: ID!, $data: ActualizarSujetoDTO!) {\n    actualizarSujeto(id: $id, data: $data)\n  }\n": typeof types.EditarTitularDocument,
    "\n  query VillaPagos($codigo: String!, $page: Int!, $limit: Int!) {\n    pagos: obtenerPagos(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: $limit, page: $page }\n    ) {\n      data {\n        __typename\n        fecha\n        operacion\n        concepto\n        metodo\n        moneda\n        monto\n        registro\n        tasa\n        total\n        unidad {\n          id\n          codigo\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": typeof types.VillaPagosDocument,
    "\n  mutation RegistrarTitular($input: RegistrarSujetoDTO!) {\n    registrarSujeto(input: $input) {\n      id\n      display_name\n    }\n  }\n": typeof types.RegistrarTitularDocument,
    "\n  query VillaPage($codigo: String!, $estado_deuda_pendiente: String!) {\n    ultimo_pago: obtenerPagos(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: 1, page: 1 }\n    ) {\n      data {\n        fecha\n        metodo\n        total\n      }\n    }\n    unidad: obtenerUnidadPorCodigo(codigo: $codigo) {\n      id\n      codigo\n      estado\n      wallet\n      deuda\n      contacto {\n        id\n        cedula\n        display_name\n        email\n        telefono\n        registro\n      }\n      titular_primario {\n        __typename\n        ... on Sujeto {\n          id\n          cedula\n          display_name\n          email\n          telefono\n        }\n      }\n      titulares {\n        __typename\n        ... on Sujeto {\n          id\n          cedula\n          display_name\n          email\n          telefono\n          registro\n        }\n        ... on Persona {\n          nombres\n          apellidos\n        }\n        ... on Ente {\n          razon_social\n          representante {\n            id\n            display_name\n            cedula\n            email\n            telefono\n          }\n        }\n      }\n    }\n    deudas_pendientes: obtenerDeudas(\n      filtro: {\n        unidad: { eq: $codigo }\n        estado: { eq: $estado_deuda_pendiente }\n      }\n    ) {\n      total\n    }\n  }\n": typeof types.VillaPageDocument,
    "\n  query VillasPage($page: Int!, $filtro: UnidadFilter, $limit: Int!) {\n    resumen: obtenerResumenUnidades {\n      total_unidades\n      unidades_solventes\n      unidades_con_pendientes\n      total_pendiente\n    }\n\n    villas: obtenerUnidades(\n      filter: $filtro\n      paginator: { limit: $limit, page: $page }\n    ) {\n      data {\n        codigo\n        estado\n        wallet\n        deuda\n        contacto {\n          id\n          email\n          telefono\n        }\n        titular_primario {\n          __typename\n          ... on Sujeto {\n            id\n            cedula\n            display_name\n          }\n          ... on Persona {\n            nombres\n            apellidos\n          }\n          ... on Ente {\n            razon_social\n          }\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": typeof types.VillasPageDocument,
    "\n  query CuotaDetalle($cuota_id: String!) {\n    cuota: obtenerCuota(id: $cuota_id) {\n      __typename\n      ... on CuotaRegular {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n      ... on CuotaEspecial {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        detalles {\n          titulo\n          descripcion\n          justificacion\n          fecha_limite\n          estado\n        }\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n      ... on CuotaSemilla {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n    }\n    deudas: obtenerDeudas(\n      filtro: { cuota: { eq: $cuota_id }, estado: { neq: \"SALDADA\" } }\n    ) {\n      data {\n        id\n        deuda\n        estado\n        unidad {\n          codigo\n        }\n        titular {\n          display_name\n        }\n      }\n    }\n  }\n": typeof types.CuotaDetalleDocument,
    "\n  query GlobalSearch($busqueda: String!, $limit: Int!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $busqueda } }\n      paginator: { limit: $limit, page: 1 }\n    ) {\n      data {\n        codigo\n        estado\n        deuda\n        titular_primario {\n          __typename\n          ... on Sujeto {\n            id\n            cedula\n            display_name\n          }\n          ... on Persona {\n            nombres\n            apellidos\n          }\n          ... on Ente {\n            razon_social\n          }\n        }\n      }\n      total\n    }\n\n    operaciones: obtenerOperaciones(\n      paginador: { limit: $limit, page: 1 }\n      filtro: {\n        or: [\n          { concepto: { like: $busqueda } }\n          { unidad: { like: $busqueda } }\n          { proveedor_nombre: { like: $busqueda } }\n        ]\n      }\n    ) {\n      data {\n        __typename\n        ... on IOperacion {\n          fecha\n          operacion\n          concepto\n          monto\n          moneda\n        }\n        ... on Pago {\n          unidad {\n            id\n            codigo\n          }\n        }\n        ... on GastoAProveedor {\n          proveedor {\n            nombre\n          }\n        }\n      }\n      total\n    }\n\n    proveedores: obtenerProveedores {\n      id\n      nombre\n      rif\n    }\n  }\n": typeof types.GlobalSearchDocument,
    "\n  query ObtenerPerodosDisponibles {\n    periodos: obtenerPeriodosDisponibles {\n      anio\n      mes\n    }\n  }\n": typeof types.ObtenerPerodosDisponiblesDocument,
    "\n  query ResumenUnidadesParaCuota {\n    resumen: obtenerResumenUnidades {\n      unidades_activas\n    }\n  }\n": typeof types.ResumenUnidadesParaCuotaDocument,
    "\n  mutation RegistrarCuota($input: RegistrarCuotaDTO!) {\n    registrarCuota(input: $input) {\n      __typename\n      ... on Cuota {\n        id\n      }\n    }\n  }\n": typeof types.RegistrarCuotaDocument,
    "\n  query RegistrarPagoOverlayUnidades($codigo_like: String!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $codigo_like } }\n      paginator: { limit: 10, page: 1 }\n    ) {\n      data {\n        id\n        codigo\n        wallet\n        deuda\n      }\n    }\n  }\n": typeof types.RegistrarPagoOverlayUnidadesDocument,
    "\n  mutation RegistrarGastoOverlay($input: RegistrarGastoDTO!) {\n    registrarGasto(input: $input) {\n      id\n      concepto\n    }\n  }\n": typeof types.RegistrarGastoOverlayDocument,
    "\n  query BuscarGastosHuerfanos($busqueda: String) {\n    gastos: obtenerGastos(\n      filter: { concepto: { like: $busqueda }, cuota: { eq: null } }\n    ) {\n      data {\n        __typename\n        ... on Gasto {\n          monto\n          total\n          operacion\n          concepto\n          metodo\n          moneda\n          tasa\n          fecha\n          metodo\n          registrado_por\n          registro\n        }\n        ... on GastoAProveedor {\n          proveedor {\n            id\n            nombre\n            rif\n            telefono\n            email\n            actualizado_en\n            creado_en\n            direccion\n          }\n        }\n      }\n    }\n  }\n": typeof types.BuscarGastosHuerfanosDocument,
    "\n    mutation RegistrarPago($input: RegistrarPagoDTO!){\n        registrarPago(input: $input) {\n            id\n        }\n    }\n": typeof types.RegistrarPagoDocument,
};
const documents: Documents = {
    "\n  query EstadoPagosVilla($filtro: DeudaFilter, $paginador: Paginator) {\n    deudas: obtenerDeudas(filtro: $filtro, paginador: $paginador) {\n      data {\n        id\n        unidad {\n          id\n          codigo\n        }\n        titular {\n          id\n          display_name\n        }\n        monto\n        deuda\n        estado\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": types.EstadoPagosVillaDocument,
    "\n  query CuotaPage($cuota_id: String!) {\n    cuota: obtenerCuota(id: $cuota_id) {\n      __typename\n      ... on Cuota {\n        id\n        mes\n        anio\n        monto\n        registro\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n              rif\n              telefono\n              email\n            }\n          }\n        }\n      }\n      ... on CuotaEspecial {\n        detalles {\n          titulo\n          descripcion\n          justificacion\n          fecha_limite\n          estado\n        }\n      }\n    }\n  }\n": types.CuotaPageDocument,
    "\n  query CuotasPage($page: Int!, $limit: Int!) {\n    cuotas: obtenerCuotas(paginator: { limit: $limit, page: $page }) {\n      data {\n        __typename\n        ... on Cuota {\n          id\n          monto\n          mes\n          anio\n          registro\n          recaudacion {\n            unidades_aplicadas\n            pagos_asociados\n            monto_estimado\n            monto_recaudado\n            moneda\n          }\n        }\n\n        ... on CuotaEspecial {\n          detalles {\n            titulo\n            descripcion\n          }\n          recaudacion {\n            unidades_aplicadas\n            pagos_asociados\n            monto_estimado\n            monto_recaudado\n            moneda\n          }\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": types.CuotasPageDocument,
    "\n  query RegistrarCuotaPage {\n    obtenerProveedores {\n      id\n      nombre\n    }\n  }\n": types.RegistrarCuotaPageDocument,
    "\n  query DashboardPage {\n    proveedores: obtenerProveedores {\n      id\n      nombre\n    }\n  }\n": types.DashboardPageDocument,
    "\n  query OperacionesPage($page: Int!, $filtro: OperacionFilter, $limit: Int!) {\n    proveedores: obtenerProveedores {\n      id\n      nombre\n    }\n\n    operaciones: obtenerOperaciones(\n      paginador: { limit: $limit, page: $page }\n      filtro: $filtro\n    ) {\n      data {\n        __typename\n\n        ... on IOperacion {\n          fecha\n          operacion\n          concepto\n          metodo\n          monto\n          moneda\n          registro\n          tasa\n          total\n        }\n\n        ... on GastoAProveedor {\n          proveedor {\n            nombre\n            rif\n            telefono\n            email\n          }\n        }\n\n        ... on Pago {\n          unidad {\n            id\n            codigo\n          }\n        }\n      }\n\n      limit\n      page\n      pages\n      total\n    }\n  }\n": types.OperacionesPageDocument,
    "\n  query UnidadTitular($codigo: String!) {\n    unidad: obtenerUnidadPorCodigo(codigo: $codigo) {\n      codigo\n      titular_primario {\n        __typename\n        ... on Sujeto {\n          id\n          display_name\n          cedula\n          email\n          telefono\n        }\n      }\n    }\n  }\n": types.UnidadTitularDocument,
    "\n  mutation Login($email: String!, $pass: String!) {\n    login(email: $email, password: $pass) {\n      token\n    }\n  }\n": types.LoginDocument,
    "\n  query RegistrarPagoPage($codigo_like: String!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $codigo_like } }\n      paginator: { limit: 5, page: 1 }\n    ) {\n      data {\n        id\n        codigo\n      }\n    }\n  }\n": types.RegistrarPagoPageDocument,
    "\n  query VillaDeudas($codigo: String!, $page: Int!, $limit: Int!) {\n    deudas: obtenerDeudas(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: $limit, page: $page }\n    ) {\n      data {\n        id\n        cuota {\n          __typename\n          ... on Deuda__Cuota {\n            id\n            nombre\n          }\n        }\n        deuda\n        monto\n        estado\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": types.VillaDeudasDocument,
    "\n  mutation EditarTitular($id: ID!, $data: ActualizarSujetoDTO!) {\n    actualizarSujeto(id: $id, data: $data)\n  }\n": types.EditarTitularDocument,
    "\n  query VillaPagos($codigo: String!, $page: Int!, $limit: Int!) {\n    pagos: obtenerPagos(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: $limit, page: $page }\n    ) {\n      data {\n        __typename\n        fecha\n        operacion\n        concepto\n        metodo\n        moneda\n        monto\n        registro\n        tasa\n        total\n        unidad {\n          id\n          codigo\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": types.VillaPagosDocument,
    "\n  mutation RegistrarTitular($input: RegistrarSujetoDTO!) {\n    registrarSujeto(input: $input) {\n      id\n      display_name\n    }\n  }\n": types.RegistrarTitularDocument,
    "\n  query VillaPage($codigo: String!, $estado_deuda_pendiente: String!) {\n    ultimo_pago: obtenerPagos(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: 1, page: 1 }\n    ) {\n      data {\n        fecha\n        metodo\n        total\n      }\n    }\n    unidad: obtenerUnidadPorCodigo(codigo: $codigo) {\n      id\n      codigo\n      estado\n      wallet\n      deuda\n      contacto {\n        id\n        cedula\n        display_name\n        email\n        telefono\n        registro\n      }\n      titular_primario {\n        __typename\n        ... on Sujeto {\n          id\n          cedula\n          display_name\n          email\n          telefono\n        }\n      }\n      titulares {\n        __typename\n        ... on Sujeto {\n          id\n          cedula\n          display_name\n          email\n          telefono\n          registro\n        }\n        ... on Persona {\n          nombres\n          apellidos\n        }\n        ... on Ente {\n          razon_social\n          representante {\n            id\n            display_name\n            cedula\n            email\n            telefono\n          }\n        }\n      }\n    }\n    deudas_pendientes: obtenerDeudas(\n      filtro: {\n        unidad: { eq: $codigo }\n        estado: { eq: $estado_deuda_pendiente }\n      }\n    ) {\n      total\n    }\n  }\n": types.VillaPageDocument,
    "\n  query VillasPage($page: Int!, $filtro: UnidadFilter, $limit: Int!) {\n    resumen: obtenerResumenUnidades {\n      total_unidades\n      unidades_solventes\n      unidades_con_pendientes\n      total_pendiente\n    }\n\n    villas: obtenerUnidades(\n      filter: $filtro\n      paginator: { limit: $limit, page: $page }\n    ) {\n      data {\n        codigo\n        estado\n        wallet\n        deuda\n        contacto {\n          id\n          email\n          telefono\n        }\n        titular_primario {\n          __typename\n          ... on Sujeto {\n            id\n            cedula\n            display_name\n          }\n          ... on Persona {\n            nombres\n            apellidos\n          }\n          ... on Ente {\n            razon_social\n          }\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n": types.VillasPageDocument,
    "\n  query CuotaDetalle($cuota_id: String!) {\n    cuota: obtenerCuota(id: $cuota_id) {\n      __typename\n      ... on CuotaRegular {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n      ... on CuotaEspecial {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        detalles {\n          titulo\n          descripcion\n          justificacion\n          fecha_limite\n          estado\n        }\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n      ... on CuotaSemilla {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n    }\n    deudas: obtenerDeudas(\n      filtro: { cuota: { eq: $cuota_id }, estado: { neq: \"SALDADA\" } }\n    ) {\n      data {\n        id\n        deuda\n        estado\n        unidad {\n          codigo\n        }\n        titular {\n          display_name\n        }\n      }\n    }\n  }\n": types.CuotaDetalleDocument,
    "\n  query GlobalSearch($busqueda: String!, $limit: Int!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $busqueda } }\n      paginator: { limit: $limit, page: 1 }\n    ) {\n      data {\n        codigo\n        estado\n        deuda\n        titular_primario {\n          __typename\n          ... on Sujeto {\n            id\n            cedula\n            display_name\n          }\n          ... on Persona {\n            nombres\n            apellidos\n          }\n          ... on Ente {\n            razon_social\n          }\n        }\n      }\n      total\n    }\n\n    operaciones: obtenerOperaciones(\n      paginador: { limit: $limit, page: 1 }\n      filtro: {\n        or: [\n          { concepto: { like: $busqueda } }\n          { unidad: { like: $busqueda } }\n          { proveedor_nombre: { like: $busqueda } }\n        ]\n      }\n    ) {\n      data {\n        __typename\n        ... on IOperacion {\n          fecha\n          operacion\n          concepto\n          monto\n          moneda\n        }\n        ... on Pago {\n          unidad {\n            id\n            codigo\n          }\n        }\n        ... on GastoAProveedor {\n          proveedor {\n            nombre\n          }\n        }\n      }\n      total\n    }\n\n    proveedores: obtenerProveedores {\n      id\n      nombre\n      rif\n    }\n  }\n": types.GlobalSearchDocument,
    "\n  query ObtenerPerodosDisponibles {\n    periodos: obtenerPeriodosDisponibles {\n      anio\n      mes\n    }\n  }\n": types.ObtenerPerodosDisponiblesDocument,
    "\n  query ResumenUnidadesParaCuota {\n    resumen: obtenerResumenUnidades {\n      unidades_activas\n    }\n  }\n": types.ResumenUnidadesParaCuotaDocument,
    "\n  mutation RegistrarCuota($input: RegistrarCuotaDTO!) {\n    registrarCuota(input: $input) {\n      __typename\n      ... on Cuota {\n        id\n      }\n    }\n  }\n": types.RegistrarCuotaDocument,
    "\n  query RegistrarPagoOverlayUnidades($codigo_like: String!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $codigo_like } }\n      paginator: { limit: 10, page: 1 }\n    ) {\n      data {\n        id\n        codigo\n        wallet\n        deuda\n      }\n    }\n  }\n": types.RegistrarPagoOverlayUnidadesDocument,
    "\n  mutation RegistrarGastoOverlay($input: RegistrarGastoDTO!) {\n    registrarGasto(input: $input) {\n      id\n      concepto\n    }\n  }\n": types.RegistrarGastoOverlayDocument,
    "\n  query BuscarGastosHuerfanos($busqueda: String) {\n    gastos: obtenerGastos(\n      filter: { concepto: { like: $busqueda }, cuota: { eq: null } }\n    ) {\n      data {\n        __typename\n        ... on Gasto {\n          monto\n          total\n          operacion\n          concepto\n          metodo\n          moneda\n          tasa\n          fecha\n          metodo\n          registrado_por\n          registro\n        }\n        ... on GastoAProveedor {\n          proveedor {\n            id\n            nombre\n            rif\n            telefono\n            email\n            actualizado_en\n            creado_en\n            direccion\n          }\n        }\n      }\n    }\n  }\n": types.BuscarGastosHuerfanosDocument,
    "\n    mutation RegistrarPago($input: RegistrarPagoDTO!){\n        registrarPago(input: $input) {\n            id\n        }\n    }\n": types.RegistrarPagoDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query EstadoPagosVilla($filtro: DeudaFilter, $paginador: Paginator) {\n    deudas: obtenerDeudas(filtro: $filtro, paginador: $paginador) {\n      data {\n        id\n        unidad {\n          id\n          codigo\n        }\n        titular {\n          id\n          display_name\n        }\n        monto\n        deuda\n        estado\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n"): typeof import('./graphql').EstadoPagosVillaDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CuotaPage($cuota_id: String!) {\n    cuota: obtenerCuota(id: $cuota_id) {\n      __typename\n      ... on Cuota {\n        id\n        mes\n        anio\n        monto\n        registro\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n              rif\n              telefono\n              email\n            }\n          }\n        }\n      }\n      ... on CuotaEspecial {\n        detalles {\n          titulo\n          descripcion\n          justificacion\n          fecha_limite\n          estado\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').CuotaPageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CuotasPage($page: Int!, $limit: Int!) {\n    cuotas: obtenerCuotas(paginator: { limit: $limit, page: $page }) {\n      data {\n        __typename\n        ... on Cuota {\n          id\n          monto\n          mes\n          anio\n          registro\n          recaudacion {\n            unidades_aplicadas\n            pagos_asociados\n            monto_estimado\n            monto_recaudado\n            moneda\n          }\n        }\n\n        ... on CuotaEspecial {\n          detalles {\n            titulo\n            descripcion\n          }\n          recaudacion {\n            unidades_aplicadas\n            pagos_asociados\n            monto_estimado\n            monto_recaudado\n            moneda\n          }\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n"): typeof import('./graphql').CuotasPageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RegistrarCuotaPage {\n    obtenerProveedores {\n      id\n      nombre\n    }\n  }\n"): typeof import('./graphql').RegistrarCuotaPageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query DashboardPage {\n    proveedores: obtenerProveedores {\n      id\n      nombre\n    }\n  }\n"): typeof import('./graphql').DashboardPageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query OperacionesPage($page: Int!, $filtro: OperacionFilter, $limit: Int!) {\n    proveedores: obtenerProveedores {\n      id\n      nombre\n    }\n\n    operaciones: obtenerOperaciones(\n      paginador: { limit: $limit, page: $page }\n      filtro: $filtro\n    ) {\n      data {\n        __typename\n\n        ... on IOperacion {\n          fecha\n          operacion\n          concepto\n          metodo\n          monto\n          moneda\n          registro\n          tasa\n          total\n        }\n\n        ... on GastoAProveedor {\n          proveedor {\n            nombre\n            rif\n            telefono\n            email\n          }\n        }\n\n        ... on Pago {\n          unidad {\n            id\n            codigo\n          }\n        }\n      }\n\n      limit\n      page\n      pages\n      total\n    }\n  }\n"): typeof import('./graphql').OperacionesPageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query UnidadTitular($codigo: String!) {\n    unidad: obtenerUnidadPorCodigo(codigo: $codigo) {\n      codigo\n      titular_primario {\n        __typename\n        ... on Sujeto {\n          id\n          display_name\n          cedula\n          email\n          telefono\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').UnidadTitularDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Login($email: String!, $pass: String!) {\n    login(email: $email, password: $pass) {\n      token\n    }\n  }\n"): typeof import('./graphql').LoginDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RegistrarPagoPage($codigo_like: String!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $codigo_like } }\n      paginator: { limit: 5, page: 1 }\n    ) {\n      data {\n        id\n        codigo\n      }\n    }\n  }\n"): typeof import('./graphql').RegistrarPagoPageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query VillaDeudas($codigo: String!, $page: Int!, $limit: Int!) {\n    deudas: obtenerDeudas(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: $limit, page: $page }\n    ) {\n      data {\n        id\n        cuota {\n          __typename\n          ... on Deuda__Cuota {\n            id\n            nombre\n          }\n        }\n        deuda\n        monto\n        estado\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n"): typeof import('./graphql').VillaDeudasDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation EditarTitular($id: ID!, $data: ActualizarSujetoDTO!) {\n    actualizarSujeto(id: $id, data: $data)\n  }\n"): typeof import('./graphql').EditarTitularDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query VillaPagos($codigo: String!, $page: Int!, $limit: Int!) {\n    pagos: obtenerPagos(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: $limit, page: $page }\n    ) {\n      data {\n        __typename\n        fecha\n        operacion\n        concepto\n        metodo\n        moneda\n        monto\n        registro\n        tasa\n        total\n        unidad {\n          id\n          codigo\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n"): typeof import('./graphql').VillaPagosDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RegistrarTitular($input: RegistrarSujetoDTO!) {\n    registrarSujeto(input: $input) {\n      id\n      display_name\n    }\n  }\n"): typeof import('./graphql').RegistrarTitularDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query VillaPage($codigo: String!, $estado_deuda_pendiente: String!) {\n    ultimo_pago: obtenerPagos(\n      filtro: { unidad: { eq: $codigo } }\n      paginador: { limit: 1, page: 1 }\n    ) {\n      data {\n        fecha\n        metodo\n        total\n      }\n    }\n    unidad: obtenerUnidadPorCodigo(codigo: $codigo) {\n      id\n      codigo\n      estado\n      wallet\n      deuda\n      contacto {\n        id\n        cedula\n        display_name\n        email\n        telefono\n        registro\n      }\n      titular_primario {\n        __typename\n        ... on Sujeto {\n          id\n          cedula\n          display_name\n          email\n          telefono\n        }\n      }\n      titulares {\n        __typename\n        ... on Sujeto {\n          id\n          cedula\n          display_name\n          email\n          telefono\n          registro\n        }\n        ... on Persona {\n          nombres\n          apellidos\n        }\n        ... on Ente {\n          razon_social\n          representante {\n            id\n            display_name\n            cedula\n            email\n            telefono\n          }\n        }\n      }\n    }\n    deudas_pendientes: obtenerDeudas(\n      filtro: {\n        unidad: { eq: $codigo }\n        estado: { eq: $estado_deuda_pendiente }\n      }\n    ) {\n      total\n    }\n  }\n"): typeof import('./graphql').VillaPageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query VillasPage($page: Int!, $filtro: UnidadFilter, $limit: Int!) {\n    resumen: obtenerResumenUnidades {\n      total_unidades\n      unidades_solventes\n      unidades_con_pendientes\n      total_pendiente\n    }\n\n    villas: obtenerUnidades(\n      filter: $filtro\n      paginator: { limit: $limit, page: $page }\n    ) {\n      data {\n        codigo\n        estado\n        wallet\n        deuda\n        contacto {\n          id\n          email\n          telefono\n        }\n        titular_primario {\n          __typename\n          ... on Sujeto {\n            id\n            cedula\n            display_name\n          }\n          ... on Persona {\n            nombres\n            apellidos\n          }\n          ... on Ente {\n            razon_social\n          }\n        }\n      }\n      limit\n      page\n      pages\n      total\n    }\n  }\n"): typeof import('./graphql').VillasPageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CuotaDetalle($cuota_id: String!) {\n    cuota: obtenerCuota(id: $cuota_id) {\n      __typename\n      ... on CuotaRegular {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n      ... on CuotaEspecial {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        detalles {\n          titulo\n          descripcion\n          justificacion\n          fecha_limite\n          estado\n        }\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n      ... on CuotaSemilla {\n        id\n        monto\n        mes\n        anio\n        registro\n        actualizacion\n        recaudacion {\n          moneda\n          monto_estimado\n          monto_recaudado\n          monto_pendiente\n          pagos_asociados\n          unidades\n          unidades_aplicadas\n          unidades_solventes\n          unidades_pendientes\n        }\n        gastos {\n          __typename\n          ... on Gasto {\n            operacion\n            concepto\n            moneda\n            monto\n            fecha\n            tasa\n            total\n          }\n          ... on GastoAProveedor {\n            proveedor {\n              id\n              nombre\n            }\n          }\n        }\n      }\n    }\n    deudas: obtenerDeudas(\n      filtro: { cuota: { eq: $cuota_id }, estado: { neq: \"SALDADA\" } }\n    ) {\n      data {\n        id\n        deuda\n        estado\n        unidad {\n          codigo\n        }\n        titular {\n          display_name\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').CuotaDetalleDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GlobalSearch($busqueda: String!, $limit: Int!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $busqueda } }\n      paginator: { limit: $limit, page: 1 }\n    ) {\n      data {\n        codigo\n        estado\n        deuda\n        titular_primario {\n          __typename\n          ... on Sujeto {\n            id\n            cedula\n            display_name\n          }\n          ... on Persona {\n            nombres\n            apellidos\n          }\n          ... on Ente {\n            razon_social\n          }\n        }\n      }\n      total\n    }\n\n    operaciones: obtenerOperaciones(\n      paginador: { limit: $limit, page: 1 }\n      filtro: {\n        or: [\n          { concepto: { like: $busqueda } }\n          { unidad: { like: $busqueda } }\n          { proveedor_nombre: { like: $busqueda } }\n        ]\n      }\n    ) {\n      data {\n        __typename\n        ... on IOperacion {\n          fecha\n          operacion\n          concepto\n          monto\n          moneda\n        }\n        ... on Pago {\n          unidad {\n            id\n            codigo\n          }\n        }\n        ... on GastoAProveedor {\n          proveedor {\n            nombre\n          }\n        }\n      }\n      total\n    }\n\n    proveedores: obtenerProveedores {\n      id\n      nombre\n      rif\n    }\n  }\n"): typeof import('./graphql').GlobalSearchDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ObtenerPerodosDisponibles {\n    periodos: obtenerPeriodosDisponibles {\n      anio\n      mes\n    }\n  }\n"): typeof import('./graphql').ObtenerPerodosDisponiblesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ResumenUnidadesParaCuota {\n    resumen: obtenerResumenUnidades {\n      unidades_activas\n    }\n  }\n"): typeof import('./graphql').ResumenUnidadesParaCuotaDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RegistrarCuota($input: RegistrarCuotaDTO!) {\n    registrarCuota(input: $input) {\n      __typename\n      ... on Cuota {\n        id\n      }\n    }\n  }\n"): typeof import('./graphql').RegistrarCuotaDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RegistrarPagoOverlayUnidades($codigo_like: String!) {\n    unidades: obtenerUnidades(\n      filter: { codigo: { like: $codigo_like } }\n      paginator: { limit: 10, page: 1 }\n    ) {\n      data {\n        id\n        codigo\n        wallet\n        deuda\n      }\n    }\n  }\n"): typeof import('./graphql').RegistrarPagoOverlayUnidadesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RegistrarGastoOverlay($input: RegistrarGastoDTO!) {\n    registrarGasto(input: $input) {\n      id\n      concepto\n    }\n  }\n"): typeof import('./graphql').RegistrarGastoOverlayDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query BuscarGastosHuerfanos($busqueda: String) {\n    gastos: obtenerGastos(\n      filter: { concepto: { like: $busqueda }, cuota: { eq: null } }\n    ) {\n      data {\n        __typename\n        ... on Gasto {\n          monto\n          total\n          operacion\n          concepto\n          metodo\n          moneda\n          tasa\n          fecha\n          metodo\n          registrado_por\n          registro\n        }\n        ... on GastoAProveedor {\n          proveedor {\n            id\n            nombre\n            rif\n            telefono\n            email\n            actualizado_en\n            creado_en\n            direccion\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').BuscarGastosHuerfanosDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RegistrarPago($input: RegistrarPagoDTO!){\n        registrarPago(input: $input) {\n            id\n        }\n    }\n"): typeof import('./graphql').RegistrarPagoDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
